#!/usr/bin/env python3
"""Generate site/privacy.html from the app repo's PRIVACY.md.

PRIVACY.md in the app repo is the source of truth. This script renders it; it
never edits it. Re-run whenever the policy changes and commit the result:

    python3 scripts/gen_privacy.py
    python3 scripts/gen_privacy.py --policy /path/to/PRIVACY.md

Handles the markdown subset the policy uses: one `#` title (replaced by the
page's own heading), `##` sections (given ids, so `[text](#slug)` links work),
paragraphs, `-` bullets with two-space continuation lines, nested bullets and
indented paragraphs inside a bullet, and the inline syntax `gen_release_notes`
already renders. Anything else passes through escaped.
"""
import argparse, html, os, re, sys

sys.dont_write_bytecode = True  # no __pycache__ beside the scripts
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_release_notes import inline, NAV  # noqa: E402

DEFAULT_POLICY = "../garage-buddy/PRIVACY.md"
OUT = "site/privacy.html"


def slug(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def inline_md(text):
    # `_italic_` is used for the "Last updated" line only.
    out = inline(text)
    return re.sub(r"(?<![\w])_([^_]+)_(?![\w])", r"<em>\1</em>", out)


def render_blocks(lines, depth=0):
    """Paragraphs and lists from already-dedented lines -> [html]."""
    out, i, pad = [], 0, "  " * depth
    while i < len(lines):
        line = lines[i]
        if not line.strip():
            i += 1
            continue
        if line.startswith("- "):
            items = []
            while i < len(lines) and (lines[i].startswith("- ") or lines[i].startswith("  ")
                                      or (not lines[i].strip() and i + 1 < len(lines)
                                          and lines[i + 1].startswith("  "))):
                if lines[i].startswith("- "):
                    items.append([lines[i][2:]])
                else:
                    items[-1].append(lines[i][2:])
                i += 1
            out.append(f"{pad}<ul>")
            for body in items:
                parts = render_blocks(body, depth + 1)
                # A bullet that is one paragraph renders without the <p>.
                if len(parts) == 1 and parts[0].lstrip().startswith("<p>"):
                    out.append(f"{pad}  <li>{parts[0].strip()[3:-4]}</li>")
                else:
                    first = parts[0].strip()
                    if first.startswith("<p>"):
                        parts[0] = first[3:-4]
                    out.append(f"{pad}  <li>" + "\n".join(p.strip() for p in parts) + "</li>")
            out.append(f"{pad}</ul>")
            continue
        para = []
        while i < len(lines) and lines[i].strip() and not lines[i].startswith("- "):
            para.append(lines[i].strip())
            i += 1
        out.append(f"{pad}<p>{inline_md(' '.join(para))}</p>")
    return out


def render(md):
    body, section = [], []

    def flush():
        if section:
            body.extend(render_blocks(section))
            section.clear()

    for line in md.splitlines():
        if line.startswith("# "):
            continue  # the page supplies its own <h1>
        m = re.match(r"^## (.+)$", line)
        if m:
            flush()
            title = m.group(1).strip()
            body.append(f'<h2 id="{slug(title)}">{inline_md(title)}</h2>')
            continue
        section.append(line)
    flush()

    nav = "\n".join(
        f'  <a href="{href}"{" aria-current=\"page\"" if href == "/privacy" else ""}>'
        f"{html.escape(label)}</a>" for href, label in NAV)
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Privacy Policy — Garage Buddy</title>
<meta name="description" content="What Garage Buddy does and does not do with your data. No servers, no analytics, no account.">
<link rel="stylesheet" href="/style.css">
</head>
<body>
<!-- Generated by scripts/gen_privacy.py from PRIVACY.md in the app repo. Do not edit by hand. -->

<nav>
{nav}
</nav>

<h1>Privacy Policy</h1>
{chr(10).join(body)}

<footer>
  <p>Garage Buddy &middot; <a href="/support">Support</a> &middot;
  <a href="mailto:shuffman@gmail.com">shuffman@gmail.com</a></p>
</footer>

</body>
</html>
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--policy", default=DEFAULT_POLICY)
    args = ap.parse_args()
    if not os.path.exists(args.policy):
        sys.exit(f"no policy at {args.policy}")
    with open(args.policy, encoding="utf-8") as f:
        page = render(f.read())
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(page)
    print(f"{OUT}: from {os.path.abspath(args.policy)}")


if __name__ == "__main__":
    main()
